version: "2.1" #Perguntar ao prof o que a versao faz
services:
  #ekar-mysql:
  # container_name: mysql-container
  #image: "mysql/mysql-server:5.7"
  #volumes:
  #  - ./dbdata:/var/lib/mysql
  #environment:
  #  MYSQL_DATABASE: user
  #  MYSQL_ROOT_PASSWORD: password
  #  MYSQL_ROOT_HOST: "%"
  # ports:
  #   - "3301:3306"
  # restart: always
  gerador-app:
    image: gerador-spring-boot-app
    build:
      context: ./Blossom_Gerador
      dockerfile: Dockerfile
    ports:
      - "8020:8020" #TODO Ver Porta no spring e mudar se necessário
  blossom-app:
    image: blossom-spring-boot-app
    build:
      context: ./blossom
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /data/blossom-spring-boot-app
    #depends_on:
    #ekar-mysql:
    # condition: service_healthy
    #gerador-app:
    #condition: service_healthy
#TODO MOVE docker-compose to main folder --> Not /blossom

#To run
#docker-compose up --build
