version: "2.1" #Perguntar ao prof o que a versao faz
services:
  ekar-mysql:
    container_name: thegeekyasian-mysql
    image: "mysql/mysql-server:5.7"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: thegeekyasian
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"

    networks:
      - all
    ports:
      - "3301:3306"
    restart: always

  gerador-app:
    image: gerador-spring-boot-app
    build:
      context: ./Blossom_Gerador
      dockerfile: Dockerfile
    networks:
      - all
    ports:
      - "8020:8020" #TODO Ver Porta no spring e mudar se necessário

  blossom-app:
    image: blossom-spring-boot-app
    build:
      context: ./blossom
      dockerfile: Dockerfile
    networks:
      - all
    ports:
      - "8080:8080"
    volumes:
      - /data/blossom-spring-boot-app

    depends_on:
      ekar-mysql:
        condition: service_healthy

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
#To run
#docker-compose up --build
